### ISSUE TITLE
user-info component missing

### ISSUE THREAD

**Issue by vsprabhakaran** [synergy2411/sbi-users-app#1]
Hi,
From what I understand, we are supposed to pass event from user-info child component to parent. But the event is passed from same child which received the event and hence there is no user-info component in this commit. 

How should we pass events from user-info child rather than user-img component

**Comment by synergy2411** [comment]
Hi,

I did not create user-info comp in project intentionally. You can generate the same. Also We want to implement Parent-Child Communication. Parent will be UsersComp and child will be UserInfoComp. Try using @Input() with PB syntax. Need not to do Child-to-parent for UserInfoComp.

**Comment by synergy2411** [comment]
> Hi,
> From what I understand, we are supposed to pass event from user-info child component to parent. But the event is passed from same child which received the event and hence there is no user-info component in this commit.
> 
> How should we pass events from user-info child rather than user-img component

Hi,

I did not create user-info comp in project intentionally. You can generate the same. Also We want to implement Parent-Child Communication. Parent will be UsersComp and child will be UserInfoComp. Try using @input() with PB syntax. Need not to do Child-to-parent for UserInfoComp.
